package io.github.hexirp.akariki

import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.{ //
  FMLInitializationEvent, FMLPostInitializationEvent, FMLPreInitializationEvent}

/** [[Initializer]] receives Forge's initialization events.
  *
  * @param context The context of initialization
  */
class Initializer(context : Context) {
  def preInit(event : FMLPreInitializationEvent, id : String, version : String) : Unit = {
    context.info("preInit")

    val metadata : ModMetadata = event.getModMetadata
    metadata.modId = id
    metadata.name = "Akariki"
    metadata.description = "Fill the world with circuits."
    metadata.url = "https://github.com/Hexirp/akariki"
    metadata.version = version
    metadata.authorList.add("Hexirp")
    metadata.autogenerated = false
  }

  def init(event : FMLInitializationEvent) : Unit = context.info("init")

  def postInit(event : FMLPostInitializationEvent) : Unit = context.info("postInit")
}
