package io.github.hexirp.akariki

import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.{ //
  FMLInitializationEvent, FMLPostInitializationEvent, FMLPreInitializationEvent}

import scala.collection.JavaConverters._

/** [[Initializer]] receives Forge's initialization events.
  *
  * @param context The context of initialization
  */
class Initializer(context : Context) {
  def preInit(event : FMLPreInitializationEvent) : Unit = {
    context.info("preInit")

    val metadata : ModMetadata = event.getModMetadata
    metadata.modId = "akariki"
    metadata.name = "Akariki"
    metadata.description = "Fill the world with circuits."
    metadata.url = "https://github.com/Hexirp/akariki"
    metadata.version = "0.1.0-alpha-1"
    metadata.authorList = List("Hexirp").asJava
    metadata.autogenerated = false
  }

  def init(event : FMLInitializationEvent) : Unit = context.info("init")

  def postInit(event : FMLPostInitializationEvent) : Unit = context.info("postInit")
}
