package io.github.hexirp.akariki

import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.{ //
  FMLInitializationEvent, FMLPostInitializationEvent, FMLPreInitializationEvent
}

import org.apache.logging.log4j.Logger

/** [[Initializer]] は Forge の初期化イベント群を受け取る。
  *
  * @param metadata The metadata of akariki
  * @param log      The logger of initialization
  */
class Initializer(metadata : Metadata, log : Logger) {
  def preInit(event : FMLPreInitializationEvent) : Unit = {
    log.info("preInit")

    val prim_meta : ModMetadata = event.getModMetadata
    prim_meta.modId = metadata.id
    prim_meta.name = metadata.name
    prim_meta.version = metadata.version
    prim_meta.description = "Fill the world with circuits."
    prim_meta.url = "https://github.com/Hexirp/akariki"
    prim_meta.authorList.add("Hexirp")
    prim_meta.autogenerated = false
  }

  def init(event : FMLInitializationEvent) : Unit = log.info("init")

  def postInit(event : FMLPostInitializationEvent) : Unit = log.info("postInit")
}
